### ISSUE TITLE
RF24 Library Won't Compile on Portenta C33

### ISSUE THREAD

**Issue by ywywmdy** [arduino/ArduinoCore-renesas#292] opened 2024-04-20 06:23 UTC
Here is a link my original post:

https://forum.arduino.cc/t/rf24-library-on-portenta-c33/1249356

After getting no responses, I submitted to Arduino and they verified they get the same error message. They suggested I post the topic here, so I did!

**Comment by per1234** [comment] 2024-04-20 10:51
Hi @ywywmdy. As I explained over on your forum post, this caused by the use of a too generic macro name in the RF24 library, which collides with an unrelated use of that name in the Renesas FSP.

Since neither of those codebases are hosted in this repository, and neither of those projects are maintained by Arduino, there is nothing we can do about it here and so I'll close this as off topic. I'll be happy to provide additional support if needed on the forum.

You are welcome to submit a report to the RF24 library maintainers:

https://github.com/nRF24/RF24

**Closed by per1234** 2024-04-20 10:51 UTC
Labels: type: imperfection, topic: code
